<?php
    session_start();
    // CERRAR LA SESION DEL USUARIO
    // TODAS LAS FUNCIONES DE SESION ESTAN INICIALIZADAS EN session_start();
    session_destroy();
    header("Location:../home.php");
    // session_destroy(); BORRA TODAS LAS SESIONES EXISTENTES
    // $_SESSION["compras"];
    // EN LAS PAGINAS SE PUEDE TENER DIFERENTES TIPOS DE SESIONES, COMO POR EJEMPLO EL DEL USUARIO Y UN CARRITO DE COMPRAS
    // AL MOMENTO DE POR EJEMPLO QUERER PASAR A FINALIZAR LA COMPRA, LO QUE SE TENDRIA QUE HACER ES CERRAR LA SESION DEL CARRITO DE COMPRAS PERO LA DEL USUARIO TENDRIA QUE SEGUIR ACTIVO, POR LO TANTO
    //FINALIZAR COMPRA
    // session_destroy($_SESSION["compras"]);
?>